# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install build
    - name: Build package
      run: python -m build
    - name: Setup CodeClimate
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
    - name: Test package
      run: |
        py.test --cov poco --cov-report=xml
    - name: Upload coverage riport
      env:
        CC_TEST_REPORTER_ID: 9d39e517e2a74afe27c5d9b783a86db53babf6c3bd498fab51605c661be3c271
      run: |
        ./cc-test-reporter after-build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: swf.operations
        password: cwS9IQ1F2NrHWtFG2otSS06zwUYUpASu6gwHexomAnS2p8boOBlT1/VGfihY9YnE8fd6G/9lo91Nqz0a0e4PGAXLzgXvEnPitVKTi5OzYrYAB6zHw1QCLeEAfD/FKOFhUW4jx05zYA5G2xTvrk+72vReASnfVFk7sz0iYhCdkkY4nB+qBacIKZIInhI7fgReU91DT05Tn92gPAXnUPQSh2HO0FTpAGgp0FCiH+ADSEFUhJkeKqz9W8QoCCqjsQFB0ye8li4JC50pE2KcL0uUyL7llJQ7ar4+ox8Yo4nzxQ8SnKVVDyGdKMyuDWCqUIJ2G31kprezQvzHTC5QRgxWGvjMRz7sBUnKEzirc5YV4kiCtGLbkQdhDifBkj/Psz5OVmDjvS6IfodkyLST5Xr7tBd341nXstUoBP08ZD5VzyxfMS+wYjf+p00NsAxa7Xwamd1lfEWd9g1VyuRL6z1XgXorYUn4uoMYRXgggP8XlusLaeShylvYV2LUL3FQmSKabn5LttT+ne+bSs+l39Wr3j/1mrKni0Ms/EPQTbgA88UMHj+HvVu8X8dPAc5vFfuPjnUhPD5hg9tWjuzYzrdl8WvtvVUdFX2UbQCFno5ueHad5ponmFcODiVLLUGfjHrqj4UPh5coO2mmKAHmwA0qGHgRMGs/dDmtdiTll9QWbuI=
