name: Test project

on:
  push:
    branches:
    - '!master'
    - '**'

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]

    name: Python ${{ matrix.python-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup CodeClimate
      run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

    - name: Test package
      run: |
        py.test --cov poco --cov-report=xml

    - name: Upload coverage riport
      env:
        CC_TEST_REPORTER_ID: 9d39e517e2a74afe27c5d9b783a86db53babf6c3bd498fab51605c661be3c271
      run: |
        ./cc-test-reporter after-build